#!/bin/bash

# Base Configuration - Override these for different deployments
export WARP_HOST_DIR="${WARP_HOST_DIR:-/mnt/host}"
export WARP_SYSTEM_DIR="${WARP_SYSTEM_DIR:-$WARP_HOST_DIR/WARP_CURRENT}"
export WARP_USER="${WARP_USER:-ubuntu}"
export WARP_GROUP="${WARP_GROUP:-ubuntu}"

# Enhanced directory structure using environment variables
export SYSTEM_DIR="$WARP_SYSTEM_DIR"
export TEMPLATES_DIR="$WARP_HOST_DIR/Templates"
export ARCHIVE_DIR="$WARP_HOST_DIR/Archive"
export BACKUP_DIR="$WARP_HOST_DIR/Backups"

# Primary System Directories
export CORE_SYSTEM="$SYSTEM_DIR"
export SYSTEM_COMMANDS_DIR="$SYSTEM_DIR/System Commands"
export WORK_LOGS_DIR="$SYSTEM_DIR/Work Logs"
export SYSTEM_LOGS_DIR="$SYSTEM_DIR/System Logs"
export WARP_RULES_DIR="$SYSTEM_DIR/Warp Rules"
export CURRENT_OBJECTIVE_DIR="$SYSTEM_DIR/Current Objective"
export FUTURE_OBJECTIVES_DIR="$SYSTEM_DIR/Future Objectives"
export PAST_OBJECTIVES_DIR="$SYSTEM_DIR/Past Objectives"
export AGENT_STATUS_DIR="$SYSTEM_DIR/Agent Status"
export TASK_POOL_DIR="$SYSTEM_DIR/Task Pool"
export DEPENDENCIES_DIR="$SYSTEM_DIR/Dependencies"
export MISSING_TASKS_DIR="$SYSTEM_DIR/Missing Tasks"
export PROMOTION_QUEUE_DIR="$SYSTEM_DIR/Promotion Queue"
export INSTALLED_TOOLS_DIR="$SYSTEM_DIR/Installed Tools"

# Critical System Files
export MAIN_RULESET="$WARP_RULES_DIR/README.md"
export SYSTEM_DOCUMENTATION="$WARP_RULES_DIR/DOCUMENTATION.md"
export PATH_REGISTRY="$SYSTEM_LOGS_DIR/PATHS.md"
export TIDY_LOG="$SYSTEM_LOGS_DIR/TIDY_LOG.md"
export ORGANIZE_LOG="$SYSTEM_LOGS_DIR/ORGANIZE_LOG.md"
export SYSTEM_STATUS="$SYSTEM_LOGS_DIR/SYSTEM_STATUS.md"
export ANOMALY_LOG="$SYSTEM_LOGS_DIR/ANOMALY_LOG.md"
export SUPERVISOR_ALERTS="$SYSTEM_LOGS_DIR/SUPERVISOR_ALERTS.md"
export AGENT_REGISTRY="$AGENT_STATUS_DIR/AGENT_REGISTRY.csv"
export MISSING_TASKS_LOG="$SYSTEM_LOGS_DIR/MISSING_TASKS_LOG.md"
export OBJECTIVE_PROMOTION_LOG="$SYSTEM_LOGS_DIR/OBJECTIVE_PROMOTION_LOG.md"
export AGENT_TIMEOUT_LOG="$SYSTEM_LOGS_DIR/AGENT_TIMEOUT_LOG.md"
export TASK_REASSIGNMENT_LOG="$SYSTEM_LOGS_DIR/TASK_REASSIGNMENT_LOG.md"
export HEARTBEAT_MONITOR="$AGENT_STATUS_DIR/HEARTBEAT_MONITOR.json"
export PERMISSION_AUDIT_LOG="$SYSTEM_LOGS_DIR/PERMISSION_AUDIT_LOG.md"
export TOOL_INSTALLATION_LOG="$SYSTEM_LOGS_DIR/TOOL_INSTALLATION_LOG.md"
export TOOLS_REGISTRY="$INSTALLED_TOOLS_DIR/TOOLS_REGISTRY.json"

#!/bin/bash

# Base environment setup
export HOME="${HOME:-$(getent passwd $(whoami) | cut -d: -f6)}"
export DEVSTACK_DIR="${DEVSTACK_DIR:-$HOME/devstack}"
export WARP_HOST_DIR="${WARP_HOST_DIR:-/mnt/host}"
export WARP_SYSTEM_DIR="${WARP_SYSTEM_DIR:-$WARP_HOST_DIR/WARP_CURRENT}"

# Agent comment system
export AGENT_COMMENTS_DIR="$DEVSTACK_DIR/agent_stack/core/comments"
export AGENT_COMMENTS_INDEX="$AGENT_COMMENTS_DIR/comment_index.json"

# Rules directory
export WARP_RULES_SOURCE="$DEVSTACK_DIR/agent_stack/core/rules"
export WARP_RULES_PATTERN="*.md"

# Ensure critical directories exist
mkdir -p "$DEVSTACK_DIR/agent_stack/core/rules"

# Primary directories
export SYSTEM_COMMANDS_DIR="$SYSTEM_DIR/System Commands"
export WORK_LOGS_DIR="$SYSTEM_DIR/Work Logs"
export SYSTEM_LOGS_DIR="$SYSTEM_DIR/System Logs"
export WARP_RULES_DIR="$SYSTEM_DIR/Warp Rules"
export CURRENT_OBJECTIVE_DIR="$SYSTEM_DIR/Current Objective"
export FUTURE_OBJECTIVES_DIR="$SYSTEM_DIR/Future Objectives"
export PAST_OBJECTIVES_DIR="$SYSTEM_DIR/Past Objectives"
export AGENT_STATUS_DIR="$SYSTEM_DIR/Agent Status"
export TASK_POOL_DIR="$SYSTEM_DIR/Task Pool"
export DEPENDENCIES_DIR="$SYSTEM_DIR/Dependencies"
export MISSING_TASKS_DIR="$SYSTEM_DIR/Missing Tasks"
export PROMOTION_QUEUE_DIR="$SYSTEM_DIR/Promotion Queue"

# Secondary directories
export TEMPLATES_DIR="$WARP_HOST_DIR/Templates"
export ARCHIVE_DIR="$WARP_HOST_DIR/Archive"
export MASTERLOG_ARCHIVE_DIR="$WORK_LOGS_DIR/Archive"
export EMERGENCY_BACKUP_DIR="$SYSTEM_DIR/Backups"
export CLOUD_SYNC_DIR="$SYSTEM_DIR/Cloud_Sync"
export SIMULATION_DIR="$SYSTEM_DIR/Simulation"
export REMOTE_CACHE_DIR="$SYSTEM_DIR/Remote_Cache"

# Critical system files
export MAIN_RULESET="$WARP_RULES_DIR/README.md"
export SYSTEM_DOCUMENTATION="$WARP_RULES_DIR/DOCUMENTATION.md"
export PATH_REGISTRY="$SYSTEM_LOGS_DIR/PATHS.md"
export TIDY_LOG="$SYSTEM_LOGS_DIR/TIDY_LOG.md"
export ORGANIZE_LOG="$SYSTEM_LOGS_DIR/ORGANIZE_LOG.md"
export SYSTEM_STATUS="$SYSTEM_LOGS_DIR/SYSTEM_STATUS.md"
export ANOMALY_LOG="$SYSTEM_LOGS_DIR/ANOMALY_LOG.md"
export SUPERVISOR_ALERTS="$SYSTEM_LOGS_DIR/SUPERVISOR_ALERTS.md"
export AGENT_REGISTRY="$AGENT_STATUS_DIR/AGENT_REGISTRY.csv"
export MISSING_TASKS_LOG="$SYSTEM_LOGS_DIR/MISSING_TASKS_LOG.md"
export OBJECTIVE_PROMOTION_LOG="$SYSTEM_LOGS_DIR/OBJECTIVE_PROMOTION_LOG.md"
export AGENT_TIMEOUT_LOG="$SYSTEM_LOGS_DIR/AGENT_TIMEOUT_LOG.md"
export TASK_REASSIGNMENT_LOG="$SYSTEM_LOGS_DIR/TASK_REASSIGNMENT_LOG.md"
export HEARTBEAT_MONITOR="$AGENT_STATUS_DIR/HEARTBEAT_MONITOR.json"
